Make nested references enable
SenseNet/sn-client pull request #1021
Opened 2020-10-14 15:47 UTC by pusztaienike

I haved tested it with this test item:

Steps:

repo: https://netcore-service.test.sensenet.com
1. Add a new AllowedChildTypes item to Sample Workspace (SmartFolder)
2. Create a New SmartFolder under Sample Workspace with the folowing options:
![image](https://user-images.githubusercontent.com/22347393/96012885-ed7eb080-0e44-11eb-890a-ee9ecdcb910f.png)
query: `+TypeIs:'Task' +Status:'Active'`
3. go to /personal-settings and copy this to the text area:
```
{
   "theme": "dark",
   "default": {
      "drawer": {
         "items": [
            {
               "itemType": "CustomContent",
               "settings": {
                  "icon": "AddAlert",
                  "title": "ActiveTask",
                  "appPath": "activeTask",
                  "root": "/Root/Content/SampleWorkspace/ActiveTask",
                  "columns": [
                     "Name",
                     "ModifiedBy/Email",
                     "ModifiedBy/Manager/Manager/Email",
                     "ModifiedBy/Manager/Name",
                     "ModifiedBy/Manager"
                  ],
                  "description": "List of accounts that should be notified"
               }
            }
         ]
      }
   }
}
```
result:
![image](https://user-images.githubusercontent.com/22347393/96013171-3fbfd180-0e45-11eb-98a9-d94cff5c56ff.png)

2020-10-15 15:15 UTC, taki9 requested changes

2020-10-15 15:15 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
>    return refWhiteList.indexOf(fieldName) !== -1 || (setting && setting.Type === 'ReferenceFieldSetting') || false
please correct it to find instead of indexOf

2020-10-20 07:35 UTC, taki9 requested changes

2020-10-20 07:35 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +        ...fields.filter((fieldName) => isReferenceField(fieldName, repo)),
it can be merged with the reduce below

2020-10-20 07:35 UTC, taki9 commented on packages/sn-client-core/src/Schemas/SchemaStore.ts
> +  public getContentTypeByName(fieldName: string): string | undefined {
getFieldTypeByName

2020-10-20 07:35 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +    const tempFieldSettings = fieldSettings
type is not allow fieldSettings to be null, can it happen?

2020-10-20 07:35 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +    const tempFieldSettings = fieldSettings
rename tempFieldSettings to a meaningful name

2020-10-20 07:35 UTC, taki9 commented on packages/sn-client-core/src/Schemas/SchemaStore.ts
> +    const tempSchemas = [...this.schemas.getValue()]
schemasCopy

2020-10-20 07:35 UTC, taki9 commented on packages/sn-client-core/src/Schemas/SchemaStore.ts
> +    const selected = tempSchemas.reduce((_, schema: Schema) => {
the created variable is not used, so return tempSchemas.reduce... is enough

2020-10-20 07:35 UTC, taki9 commented on packages/sn-client-core/src/Schemas/SchemaStore.ts
> +    const selected = tempSchemas.reduce((_, schema: Schema) => {
rename selected

2020-10-20 07:35 UTC, taki9 commented on packages/sn-client-core/src/Schemas/SchemaStore.ts
> +      const field = schema.FieldSettings.find((fieldSetting: FieldSetting) => fieldSetting.Name === fieldName)?.Type
rename field

2020-10-20 08:20 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +          .getSchemaByName(displayField.Type)
displayField can be null

2020-11-09 07:43 UTC, herflis approved these changes

2020-11-16 08:40 UTC, taki9 requested changes

2020-11-16 08:40 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +              if (isReferenceField(fieldName.split('/')[0], repo, props.schema)) {
splittedFieldName[0] instead of fieldName.split('/')[0]

2020-11-16 08:40 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +                referenceFields.push(fieldName.split('/')[0])
splittedFieldName[0] instead of fieldName.split('/')[0]

2020-11-16 08:40 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +              !referenceFields.find((ref) => ref === fieldName) && referenceFields.push(fieldName)
referenceFields.includes

2020-11-16 08:40 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +              !referenceFields.find((ref) => ref === PathHelper.getParentPath(fieldName)) &&
referenceFields.includes

2020-11-16 08:40 UTC, taki9 commented on apps/sensenet/src/components/content-list/content-list.tsx
> +        .getSchemaByName(displayField?.Type)
parameter of getSchemaByName can only be a string

2020-11-16 08:40 UTC, taki9 commented on apps/sensenet/src/components/dialogs/reference-content-list/reference-list.tsx
> +        actionName: 'new',
should it match with the 3rd parameter of getControlForContentField? if yes, which is the correct?

2020-11-16 08:43 UTC, taki9 commented
![image](https://user-images.githubusercontent.com/8918642/99230793-071e6980-27f0-11eb-8172-fc7f2f61e724.png)

Tooltip is throwing error to console when no value is provided. In this case I created a "ModifiedBy/Manager/Manager/Email" column, but the ModifiedBy user had no Manager.

2020-11-16 13:28 UTC, pusztaienike commented
> ![image](https://user-images.githubusercontent.com/8918642/99230793-071e6980-27f0-11eb-8172-fc7f2f61e724.png)
> 
> Tooltip is throwing error to console when no value is provided. In this case I created a "ModifiedBy/Manager/Manager/Email" column, but the ModifiedBy user had no Manager.

Done

2020-11-16 14:30 UTC, taki9 approved these changes

2020-11-16 16:45 UTC, merged