added E2E test for header and dashboard
SenseNet/sn-client pull request #1025
Opened 2020-10-18 03:32 UTC by NileshPatel17

added E2Ee test for #911

2020-10-18 03:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/SenseNet/sn-client?pullRequest=1025) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/SenseNet/sn-client?pullRequest=1025) before we can accept your contribution.<br/><hr/>**Nilesh Patel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/SenseNet/sn-client?pullRequest=1025) it.</sub>

2020-10-19 07:31 UTC, herflis requested changes

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('h1').contains(/Welcome to your [a-z0-9]+ project/)
please add a `data-test` attribute to the h1 element (as you did with the header) and select the element by this attr

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    expect('3 users').to.match(/[0-3] users/)
please add a `data-test` attribute to the element (as you did with the header) and select the element by this attribute

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    expect('500 content').to.match(/[0-500] content/)
please add a `data-test` attribute to the element (as you did with the header) and select the element by this attribute

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    expect('1 GB storage space').to.match(/[0-1] GB storage space/)
please add a `data-test` attribute to the element (as you did with the header) and select the element by this attribute

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    expect('3 of 3 used').to.match(/[0-3] of 3 used/)
please add a `data-test` attribute to the element (as you did with the header) and select the element by this attribute

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    expect('21 of 500 used').to.match(/[0-9] of 500 used/)
please add a `data-test` attribute to the element (as you did with the header) and select the element by this attribute

2020-10-19 07:31 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    expect('0 of 1 GB used').to.match(/[0-1] of 1 GB used/)
please add a `data-test` attribute to the element (as you did with the header) and select the element by this attribute

2020-10-19 12:38 UTC, NileshPatel17 commented
All requested changes are done.

2020-10-19 15:01 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('[data-test="usage-contents"]').contains(/[0-9] of 500 used/)
```suggestion
    cy.get('[data-test="usage-contents"]').contains(/[0-500] of 500 used/)
```

2020-10-19 15:10 UTC, NileshPatel17 commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('[data-test="usage-contents"]').contains(/[0-9] of 500 used/)
Done

2020-10-20 08:13 UTC, herflis requested changes

2020-10-20 08:13 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('[data-test="feature-content"]').contains(/[0-500] content/)
```suggestion
    cy.get('[data-test="feature-content"]').contains(/([0-9]|[1-8][0-9]|9[0-9]|[1-4][0-9]{2}|500) content/)
```

2020-10-20 08:13 UTC, herflis commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('[data-test="usage-contents"]').contains(/[0-500] of 500 used/)
```suggestion
    cy.get('[data-test="usage-contents"]').contains(/[0-9]|[1-8][0-9]|9[0-9]|[1-4][0-9]{2}|500 of 500 used/)
```

2020-10-20 08:23 UTC, NileshPatel17 commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('[data-test="feature-content"]').contains(/[0-500] content/)
@herflis changes done

2020-10-20 08:23 UTC, NileshPatel17 commented on apps/sensenet/cypress/integration/dashboard/dashboard.spec.ts
> +    cy.get('[data-test="usage-contents"]').contains(/[0-500] of 500 used/)
@herflis changes done

2020-10-20 09:01 UTC, merged

2020-10-20 09:01 UTC, herflis commented
@NileshPatel17 thank you for taking the time to help us! We greatly appreciate your contribution, you will get the extra sensenet-Hacktoberfest swag 🧦. We will contact you via email after the Hacktoberfest event. Hope you are having a great Hacktoberfest! 🎉 🙂