WIP - DocViewer refact
SenseNet/sn-client pull request #1027
Opened 2020-10-20 06:59 UTC by pusztaienike

2020-11-16 08:06 UTC, herflis approved these changes

2020-11-20 10:40 UTC, taki9 requested changes

2020-11-27 12:12 UTC, taki9 requested changes
- after opening a doc with multiple pages, isPreviewAvailable requests are out of control on scoll :D

- uploaded a test document, opened it, clicked on generate button
  - after this I waited a minute or two for pageCount change from -1 but it not happened, so closed the doc and reopened it: 
![empty-page](https://user-images.githubusercontent.com/8918642/100448075-05875800-30b2-11eb-82e0-0411690cac8f.PNG)
data request fired ca. per second, but empty page is shown

2020-11-27 12:12 UTC, taki9 commented on packages/sn-document-viewer-react/src/hooks/usePreviewImage.ts
> +            const oldValueIndex = newImages.findIndex((image) => image.Index === pageNo)
do it with images.imageData.map

2020-11-27 12:12 UTC, taki9 commented on packages/sn-document-viewer-react/src/hooks/usePreviewImage.ts
> +      !images.imageData.find((i) => i.Index === pageNo)?.PreviewImageUrl
store in a variable, should not iterate twice for the data

2020-11-27 12:15 UTC, taki9 requested changes

2020-11-27 12:15 UTC, taki9 commented on packages/sn-client-core/src/Repository/Preview.ts
> +        version: options.version && options.version,
```suggestion
        version: options.version
```

2020-11-30 13:21 UTC, pusztaienike commented on packages/sn-document-viewer-react/src/hooks/usePreviewImage.ts
> +            const oldValueIndex = newImages.findIndex((image) => image.Index === pageNo)
cannot do with map :(

2020-12-02 13:32 UTC, taki9 requested changes
- comment marker should point to the same part of the document after rotation
- image only load after scrolling even if PreviewAvailable request had response before it
- open a large document with a lot of pages, go to one of the last pages with the page input: a lot of PreviewAvailable request fired, we should only request for the given page (and maybe 1 or 2 around).
- a little debouce would be great for PreviewAvailable on scrolling (try to scroll with the browser scrollbar on a large document, and a lot of request fired)

2020-12-07 11:54 UTC, taki9 approved these changes

2020-12-07 14:25 UTC, merged