added e2e test case for edit content
SenseNet/sn-client pull request #1052
Opened 2020-10-31 05:01 UTC by NileshPatel17

2020-10-31 06:28 UTC, herflis commented on apps/sensenet/cypress/integration/edit-content/edit-content.spec.ts
> +          console.log($el.text())
remove the console log please

2020-10-31 06:29 UTC, herflis commented on apps/sensenet/cypress/integration/edit-content/edit-content.spec.ts
> +  it('Test case 1: edit content should works properly.', () => {
```suggestion
  it('Test case 1: edit content should work properly.', () => {
```

2020-10-31 06:30 UTC, herflis requested changes

2020-10-31 06:30 UTC, herflis commented on apps/sensenet/cypress/integration/edit-content/edit-content.spec.ts
> +  it('Test case 2: edit content should works properly.', () => {
```suggestion
  it('Test case 2: edit content should work properly.', () => {
```

2020-10-31 06:34 UTC, NileshPatel17 commented on apps/sensenet/cypress/integration/edit-content/edit-content.spec.ts
> +          console.log($el.text())
Removed

2020-10-31 06:34 UTC, NileshPatel17 commented on apps/sensenet/cypress/integration/edit-content/edit-content.spec.ts
> +  it('Test case 1: edit content should works properly.', () => {
Done

2020-10-31 06:34 UTC, NileshPatel17 commented on apps/sensenet/cypress/integration/edit-content/edit-content.spec.ts
> +  it('Test case 2: edit content should works properly.', () => {
Done

2020-10-31 17:35 UTC, herflis requested changes

2020-11-01 02:21 UTC, NileshPatel17 commented
@herflis Changes are done.

2020-11-01 06:41 UTC, herflis commented
Thank you @NileshPatel17

2020-11-01 06:42 UTC, merged