added e2e test case for groups
SenseNet/sn-client pull request #1056
Opened 2020-10-31 10:51 UTC by NileshPatel17

added e2e test  cases for #908

2020-10-31 17:38 UTC, herflis requested changes

2020-10-31 17:38 UTC, herflis commented on apps/sensenet/cypress/integration/groups/groups.spec.ts
> +    cy.get('button[aria-label="Cancel"]').click()
```suggestion
    cy.get('[data-test="cancel"]').click()
```

2020-11-01 02:30 UTC, NileshPatel17 commented
@herflis changes are done as requested.

2020-11-01 06:44 UTC, herflis commented
Thank you @NileshPatel17

2020-11-01 06:44 UTC, merged