Advanced search
SenseNet/sn-client pull request #1180
Opened 2021-02-05 16:26 UTC by taki9

2021-02-10 10:17 UTC, pusztaienike reviewed
I could not save a search with the following data:
keyword: 'Sample',
modificationDate: 'today'

I got 'Unexpected end of JSON input' error, but response number 200 from backend, but saved queries was empty:

request payload:
```
{query: "(Name:'Sample*' OR DisplayName:'Sample*') AND (ModificationDate:>=@@Today@@)",…}
displayName: "Search results for 'Sample'"
query: "(Name:'Sample*' OR DisplayName:'Sample*') AND (ModificationDate:>=@@Today@@)"
queryType: "Public"
uiFilters: "{"term":"Sample","filters":{"type":{"name":"all","icon":{"type":{"type":{},"compare":null},"key":null,"ref":null,"props":{},"_owner":null}},"date":{"name":"modifiedToday","query":{"field":"ModificationDate","value":"@@Today@@"}},"reference":{"name":"anybody"}}}"
```

2021-02-11 15:51 UTC, herflis requested changes
- the clear button should have a tooltip
- the clear button does not clear the value of the textbox
![search-clear](https://user-images.githubusercontent.com/6968860/107657804-ccf52480-6c85-11eb-862d-7c4ebb11b819.gif)
- (after the clear button disappeared the save query button did not work either)
- cannot navigate up in the picker from lower level containers

2021-02-17 07:28 UTC, herflis approved these changes

2021-02-17 10:32 UTC, pusztaienike approved these changes

2021-02-17 13:54 UTC, merged