Todo app refactor: first step
SenseNet/sn-client pull request #1232
Opened 2021-03-08 15:24 UTC by pusztaienike

2021-03-10 08:36 UTC, huszerlbence reviewed
approved after color changes (highlight color and "completed" color).

nice one,
thanks

2021-03-11 12:49 UTC, huszerlbence approved these changes
Checked the modified files and found the hex code of the new color : )
thanks

2021-03-25 14:51 UTC, taki9 commented on examples/sn-react-tasklist/src/app.tsx
>  // end of material imports
remove the comments

2021-03-25 14:51 UTC, taki9 commented on examples/sn-react-tasklist/src/app.tsx
>  import Toolbar from '@material-ui/core/Toolbar'
import this like the ones above

2021-04-09 13:13 UTC, taki9 requested changes
Remove sn-universal-header from packages. The merge messed it up.

2021-04-09 13:13 UTC, taki9 commented on examples/sn-react-tasklist/package.json
> +    "@sensenet/universal-header": "^1.0.0",
```suggestion
    "@sensenet/universal-header-react": "^1.0.0",
```

2021-04-12 10:08 UTC, taki9 approved these changes

2021-04-12 14:32 UTC, herflis approved these changes

2021-04-12 15:29 UTC, merged