Create new tests for users and groups
SenseNet/sn-client pull request #1242
Opened 2021-03-16 14:25 UTC by taki9

2021-03-19 15:12 UTC, pusztaienike approved these changes
🌞

2021-03-24 09:29 UTC, herflis requested changes

2021-03-24 09:29 UTC, herflis commented on apps/sensenet/cypress/integration/groups/groups.spec.ts
> +  it('ensures that creation of a new group is work properly', () => {
```suggestion
  it('ensures that creation of a new group is working properly', () => {
```

2021-03-24 09:29 UTC, herflis commented on apps/sensenet/cypress/integration/groups/groups.spec.ts
> +  it('ensures that deletion of a group is work properly', () => {
```suggestion
  it('ensures that deletion of a group is working properly', () => {
```

2021-03-24 09:29 UTC, herflis commented on apps/sensenet/cypress/integration/users-and-groups.spec.ts
> +  it('ensures that deletion of users is work properly', () => {
```suggestion
  it('ensures that deletion of users is working properly', () => {
```

2021-03-24 09:29 UTC, herflis commented on apps/sensenet/cypress/integration/users-and-groups.spec.ts
> +  it('ensures that the creation of a new users is work properly', () => {
```suggestion
  it('ensures that the creation of new users is working properly', () => {
```

2021-03-29 10:12 UTC, merged