Icon rework
SenseNet/sn-client pull request #1252
Opened 2021-03-23 08:44 UTC by taki9

2021-03-25 08:21 UTC, pusztaienike requested changes
There are some icons what changed, but I think the old version was so much better, than the new.
Could you please replace these to the "old version"?
![2021-03-25_09h12_01](https://user-images.githubusercontent.com/22347393/112441158-69154f80-8d4b-11eb-971b-abc5d037a985.png)
![2021-03-25_09h12_27](https://user-images.githubusercontent.com/22347393/112441161-6a467c80-8d4b-11eb-9228-19970aaba21c.png)
![2021-03-25_09h16_05](https://user-images.githubusercontent.com/22347393/112441165-6b77a980-8d4b-11eb-89b1-36e8bb4cce95.png)
![2021-03-25_09h16_18](https://user-images.githubusercontent.com/22347393/112441168-6ca8d680-8d4b-11eb-9365-a37481a58ef4.png)

2021-03-25 08:34 UTC, herflis commented
@pusztaienike the other pr's with the ctd icon changes are not merged yet, so these are not the final version of them :)

2021-03-31 16:03 UTC, herflis approved these changes

2021-04-07 07:11 UTC, pusztaienike commented
Trash is still not okay, 
Under sample ws Links, Memos, Tasks are different than before
![image](https://user-images.githubusercontent.com/22347393/113825279-11caa280-9781-11eb-93cd-a66fee163f7a.png)
![image](https://user-images.githubusercontent.com/22347393/113825297-17c08380-9781-11eb-97af-f58ed96460ca.png)

2021-04-13 07:20 UTC, pusztaienike approved these changes

2021-04-13 08:05 UTC, merged