Make webhook payload editable
SenseNet/sn-client pull request #1279
Opened 2021-04-12 12:27 UTC by pusztaienike

2021-04-12 12:55 UTC, herflis requested changes

2021-04-12 12:55 UTC, herflis commented on apps/sensenet/src/localization/default.ts
> +      'Custom payload can be any valid JSON value. To resolve a value from the original webhook payload use a JSON pointer wrapped with curly braces.',
```suggestion
      'Custom payload can be any valid JSON value. If you want to use the default payload, leave the textbox empty.',
```

2021-04-12 17:33 UTC, taki9 commented on apps/sensenet/src/components/field-controls/webhook-payload.tsx
>      },
```
      '&:focus': {
        outlineColor: theme.palette.primary.main,
      },
```

2021-04-13 06:19 UTC, taki9 commented on apps/sensenet/src/components/field-controls/webhook-payload.tsx
> +      ? props.settings.DefaultValue
prettify this default also?

2021-04-13 08:22 UTC, herflis approved these changes

2021-04-13 10:05 UTC, taki9 approved these changes

2021-04-13 10:27 UTC, merged