Settings - Stats addition (from versionInfo)
SenseNet/sn-client pull request #1287
Opened 2021-04-14 12:41 UTC by pusztaienike

2021-04-22 13:37 UTC, taki9 commented on apps/sensenet/src/components/settings/stats-components-widget.tsx
> +          {props.data.LatestReleases.find((item) => item.ProductName === 'SenseNet.Services') &&
store it in a variable

2021-04-22 13:37 UTC, taki9 commented on apps/sensenet/src/components/settings/stats-components-widget.tsx
> +          {props.data.LatestReleases.find((item) => item.ProductName === 'SenseNet.AdminUI') &&
store it in a variable

2021-04-22 13:37 UTC, taki9 commented on apps/sensenet/src/components/settings/stats-components-widget.tsx
> +              props.data.LatestReleases.find((item) => item.ProductName === 'SenseNet.Services')!.ReleaseData,
ReleaseData? backend typo? 😄

2021-04-28 06:20 UTC, herflis requested changes

2021-04-28 06:20 UTC, herflis commented on apps/sensenet/src/localization/default.ts
> +      'Components of your sensenet. A component can consist of several packages, but there is also possible that a component is from only a single package.',
```suggestion
      'Components of your sensenet instance. These components may include one or more packages.',
```

2021-04-28 06:20 UTC, herflis commented on apps/sensenet/src/localization/default.ts
> +      'These packages make up the components of sensenet. There can also be packages that are not involved in the structure of the components, such as a tool-type package designed to run multiple tim
```suggestion
      'These packages are mainly the building bricks of sensenet components. There are tool-like packages that are not part of the component structure, they were made to run multiple times, for example delete or index content.',
```

2021-04-28 06:31 UTC, herflis requested changes
Till we rethink the headings I think we could add the same font size to the `rowContainer` as it has in the API and Security page. This change should be made in
- stats-components-widget.tsx
- stats-installed-packages-widget.tsx
- stats-storage-widget.tsx

2021-04-28 06:31 UTC, herflis commented on apps/sensenet/src/components/settings/stats-components-widget.tsx
>        padding: '10px 0',
```suggestion
      padding: '10px 0',
      fontSize: '16px',
```

2021-05-03 12:13 UTC, taki9 approved these changes

2021-05-04 15:57 UTC, herflis approved these changes

2021-05-05 07:22 UTC, merged