Link to current user's edit view
SenseNet/sn-client pull request #1292
Opened 2021-04-15 08:17 UTC by pusztaienike

NOTE: It is not working with builtin users!!

2021-04-19 13:53 UTC, herflis approved these changes
✨

2021-04-22 13:24 UTC, taki9 requested changes

2021-04-22 13:24 UTC, taki9 commented on apps/sensenet/src/components/appbar/desktop-nav-menu.tsx
> +                      newParams: { content: `${currentUser.Path.replace('/Root/IMS/Public', '')}` },
```suggestion
                      newParams: { content: `${currentUser.Path.replace(PATHS.usersAndGroups.snPath, '')}` },
```

2021-04-27 08:02 UTC, taki9 approved these changes

2021-05-03 12:14 UTC, taki9 requested changes
close the menu after click

2021-05-05 08:16 UTC, taki9 approved these changes

2021-05-05 11:11 UTC, merged