Test & Bugfix - Permission editor main page links
SenseNet/sn-client pull request #1322
Opened 2021-05-11 13:36 UTC by pusztaienike

2021-05-12 11:53 UTC, herflis approved these changes

2021-05-19 09:02 UTC, taki9 requested changes

2021-05-19 09:02 UTC, taki9 commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +                                  newParams: { content: inheritedEntry.ancestor?.replace('/Root/Content', '') },
getUrlForContent is the right function to use, we should debug why it returns a bad url

2021-05-28 12:03 UTC, taki9 approved these changes

2021-05-28 13:19 UTC, merged