Fix GitHub repo url in the example app menus
SenseNet/sn-client pull request #1329
Opened 2021-05-18 13:16 UTC by herflis

UniversalHeader got a new prop 'name' to propagate package name to the apps

2021-05-19 09:09 UTC, taki9 commented on packages/sn-universal-header-react/src/components/header.tsx
> +  name: string
how will you know some months later what the name parameter meant to be?

2021-05-19 09:09 UTC, taki9 commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +                    : 'https://github.com/SenseNet/sn-client/tree/master/examples/sn-react-tasklist'
https://github.com/SenseNet/sn-client/tree/master/examples would be a better default value

2021-05-20 09:47 UTC, pusztaienike requested changes

2021-05-20 09:47 UTC, pusztaienike commented on examples/sn-react-component-docs/stories/universal-header.stories.tsx
> +        appName="sn-react-imagegallery"
```suggestion
        appName="sn-react-component-docs"
```

2021-05-20 11:11 UTC, taki9 approved these changes

2021-05-20 15:28 UTC, pusztaienike approved these changes

2021-05-20 16:57 UTC, merged