Dashboard learn section fixes
SenseNet/sn-client pull request #1335
Opened 2021-05-20 17:24 UTC by herflis

2021-05-21 14:58 UTC, pusztaienike approved these changes
👽

2021-05-25 08:50 UTC, taki9 requested changes
> buttons should have the same labels as seen on design

2021-05-25 09:25 UTC, huszerlbence approved these changes
checked on the test site and everything seems good to me.
thanks

2021-05-28 12:18 UTC, taki9 requested changes

2021-05-28 12:18 UTC, taki9 commented on apps/sensenet/src/components/field-controls/webhook-payload.tsx
> +          </Paper>
```tsx
{useDefault ? 
  <Typography variant="body1" gutterBottom={true}>
    {localization.webhooksPayload.defaultPayload} 
  </Typography>
:
  <Paper elevation={0} className={widgetClasses.container}>
    <pre className={classes.defaultPayload}>{value}</pre>
  </Paper>
}
```

- rename classes.defaultPayload to classes.payload (it is the customized one)
- remove localization.webhooksPayload.customize

2021-06-01 07:01 UTC, taki9 approved these changes

2021-06-01 12:40 UTC, merged