Example app features and fixes
SenseNet/sn-client pull request #1341
Opened 2021-05-28 15:33 UTC by pusztaienike

**sn-react-browser:**
_docviewer:_
docviewer was unusable, because of styling problems (only 2 pages were visible, action buttons were also invisible)
there was no "Close" button on docviewer
saveWidget makes no sense here
_others:_
add Go to repo button
change header

**sn-react-calendar:**
add Go to repo button
change header

**sn-react-imagegallery:**
add Go to repo button

**sn-react-memoapp:**
add Go to repo button
change header

**sn-react-tasklist**
add Go to repo button

**sn-react-usersearch**
add Go to repo button
change header

2021-06-01 15:40 UTC, taki9 requested changes

2021-06-01 15:40 UTC, taki9 commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +    setIsPopperOpen(!isMobile)
why? maybe you want to close it when screen size changes?

2021-06-01 15:40 UTC, taki9 commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +      width: '281px',
why not auto?

2021-06-01 15:40 UTC, taki9 commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +        <Paper className={clsx(classes.popperWrapper, { [classes.popperWrapperMobile]: isMobile })}>
drawer would have been easier

2021-06-01 15:40 UTC, taki9 commented on packages/sn-universal-header-react/src/hooks/media-query-override.ts
> +}
dont do this, this logic only used in one component (and its name also bad)

2021-06-02 12:41 UTC, pusztaienike commented on examples/sn-react-browser/src/components/document-viewer.tsx
> +      color: '#FFFFFF',
I could not reproduce this. Can you please check again after cache delete? 🤔

2021-06-02 12:42 UTC, pusztaienike commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +        <Paper className={clsx(classes.popperWrapper, { [classes.popperWrapperMobile]: isMobile })}>
Discussed: no changes needed

2021-06-07 06:21 UTC, taki9 requested changes

2021-06-07 06:21 UTC, taki9 commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +  console.log(isUnderMd)
remove console log

2021-06-07 06:21 UTC, taki9 commented on packages/sn-universal-header-react/src/components/hamburger-menu.tsx
> +      width: 'auto',
default value of width is auto

2021-06-07 06:55 UTC, herflis approved these changes

2021-06-07 13:53 UTC, taki9 approved these changes

2021-06-07 14:10 UTC, merged