editor localization
SenseNet/sn-client pull request #1351
Opened 2021-06-10 13:36 UTC by taki9

2021-06-11 08:04 UTC, pusztaienike commented on packages/sn-editor-react/src/context/localization-context.tsx
> +export const defaultLocalization = {
hungarian?

2021-06-14 14:20 UTC, herflis requested changes

2021-06-14 14:20 UTC, herflis commented on apps/sensenet/src/localization/hungarian.ts
> +      openInNewTab: 'Hivatkozás új lapon történő megnyitása',
```suggestion
      openInNewTab: 'Megnyitás új lapon',
```

2021-06-14 14:20 UTC, herflis commented on packages/sn-editor-react/src/context/localization-context.tsx
> +    alignJustify: 'Align justify',
```suggestion
    alignJustify: 'Justify',
```

2021-06-16 13:37 UTC, pusztaienike approved these changes

2021-06-25 06:58 UTC, merged