Editor unit tests and minor fixes
SenseNet/sn-client pull request #1366
Opened 2021-06-17 07:03 UTC by taki9

2021-06-21 06:53 UTC, herflis requested changes

2021-06-21 06:53 UTC, herflis commented on packages/sn-editor-react/test/editor.test.tsx
> +  it('should render properly', () => {
```suggestion
  it('should be rendered properly', () => {
```

2021-06-21 06:53 UTC, herflis commented on packages/sn-editor-react/test/editor.test.tsx
> +  it('should render placeholder if no content passed', () => {
```suggestion
  it('should render placeholder if no content is passed', () => {
```

2021-06-21 06:53 UTC, herflis commented on packages/sn-editor-react/test/image-control.test.tsx
> +  it('should render properly', () => {
```suggestion
  it('should be rendered properly', () => {
```

2021-06-21 06:53 UTC, herflis commented on packages/sn-editor-react/test/link-control.test.tsx
> +  it('should render properly', () => {
```suggestion
  it('should be rendered properly', () => {
```

2021-06-21 06:53 UTC, herflis commented on packages/sn-editor-react/test/link-control.test.tsx
> +  it('should not open dialog when no text selected', () => {
```suggestion
  it('should not open dialog when no text is selected', () => {
```

2021-06-21 06:53 UTC, herflis commented on packages/sn-editor-react/test/typography-control.test.tsx
> +  it('should render properly', () => {
```suggestion
  it('should be rendered properly', () => {
```

2021-06-30 06:51 UTC, pusztaienike approved these changes
Don't forget the conflicts!

2021-07-07 13:59 UTC, merged