Gatbsy tasks
SenseNet/sn-client pull request #1367
Opened 2021-06-17 13:31 UTC by pusztaienike

2021-06-29 06:38 UTC, herflis approved these changes

2021-07-08 13:17 UTC, taki9 requested changes

2021-07-08 13:17 UTC, taki9 commented on packages/gatsby-source-sensenet/.npmignore
> +yarn.lock
duplicated

2021-07-08 13:17 UTC, taki9 commented on packages/gatsby-source-sensenet/README.md
> +RichText is a field type that enables authors to create rich text content. By default sensenet will provide you the field as HTML format but there is also possible to get the response as JSON. For ge
JSON can be rendered with rendetHtml method from @sensenet/editor-react package.

2021-07-08 13:19 UTC, taki9 requested changes
folder of the example and its package.json file came back with dependency upgrade

2021-07-13 14:49 UTC, taki9 approved these changes

2021-07-14 07:13 UTC, merged