Upload existing file
SenseNet/sn-client pull request #1414
Opened 2022-07-28 09:12 UTC by hashtagnulla

2022-07-29 11:36 UTC, tusmester requested changes

2022-07-29 11:36 UTC, tusmester commented on apps/sensenet/src/localization/hungarian.ts
> +      `Ezzel a névvel (<span style='color: #26a69a'><b>${fileName}</b></span>) már létezik fájl. Szeretné lecseréni?`,
```suggestion
      `Ezzel a névvel (<span style='color: #26a69a'><b>${fileName}</b></span>) már létezik fájl. Szeretné lecserélni?`,
```

2022-08-02 06:02 UTC, Restobit approved these changes

2022-08-08 09:50 UTC, tusmester approved these changes

2022-08-08 09:53 UTC, merged