Permission editor main page
SenseNet/sn-client pull request #759
Opened 2020-07-24 15:37 UTC by pusztaienike

2020-08-14 07:22 UTC, herflis commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +          <ListItemText primary="Set on this content" className={classes.listTitle} />
Could this primary text be localized?

2020-08-14 07:23 UTC, herflis commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +          <ListItemText primary="Inherited from ancestor" className={classes.listTitle} />
Could this primary text be localized? :)

2020-08-17 06:50 UTC, herflis commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +        const result = await repo.executeAction<any, AclResponseType>({
I think GetAcl should be moved to `repository.security` in the client-core package

2020-09-09 06:29 UTC, herflis approved these changes

2020-09-16 21:30 UTC, taki9 requested changes

2020-09-16 21:30 UTC, taki9 commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +          {permissions?.entries.filter((entry) => entry.inherited === false).length === 0 ? (
store the filtered array in a variable to gain performance

2020-09-16 21:30 UTC, taki9 commented on packages/sn-client-core/src/Models/SecurityModels.ts
> +export class PermissionType {
use interfaces for types

2020-09-16 21:30 UTC, taki9 commented on packages/sn-client-core/src/Repository/Security.ts
> +      body: undefined,
get request has no body, so simply remove this option here

2020-09-16 21:30 UTC, taki9 commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +      cursor: 'pointer',
color, cursor and hover underline are already set by material-ui classes

2020-09-16 21:30 UTC, taki9 commented
I think a Cancel button would be useful in the right bottom corner.

2020-09-17 11:00 UTC, pusztaienike commented
> I think a Cancel button would be useful in the right bottom corner.

Done

2020-09-18 11:13 UTC, taki9 approved these changes

2020-09-18 12:11 UTC, merged