Permission editor dialog additional features
SenseNet/sn-client pull request #835
Opened 2020-09-02 14:49 UTC by pusztaienike

- [X] localOnly flag
- [] members tab -WIP

2020-09-07 07:52 UTC, herflis approved these changes

2020-09-18 11:11 UTC, taki9 requested changes

2020-09-18 11:11 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor/permission-editor-members.tsx
> +import { reactControlMapper } from '@sensenet/controls-react'
it is almost the same exact code as in reference-content-list, we should create a new common component, which is customizable with props for the unique requirements. or make reference-content-list customizable for changes in these case, if that possible

2020-09-18 11:11 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor/permission-editor-members.tsx
> +import { reactControlMapper } from '@sensenet/controls-react'
ok, now i see, you tried it, could we improve that?

2020-09-21 09:09 UTC, taki9 approved these changes

2020-09-21 09:11 UTC, merged