implement assignNewEntry feature
SenseNet/sn-client pull request #838
Opened 2020-09-04 13:27 UTC by pusztaienike

- [X] Implement assign new entry feature
- [X] Fix selected CSS style on List Items when open permission-editor-dialog

2020-09-09 06:36 UTC, herflis approved these changes

2020-09-20 14:41 UTC, taki9 requested changes

2020-09-20 14:41 UTC, taki9 commented on apps/sensenet/src/components/dialogs/member-select-dialog.tsx
> +              Description: 'Type in a name',
localization

2020-09-20 14:41 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor-dialog.tsx
> +                props.callBackFunction?.()
it is not the best solution, is it possible to refesh right after new entry has added or here, but only in that case?

2020-09-20 14:41 UTC, taki9 commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +      const localPermissions = { ...permissions }
permissions.entries.push(newEntry) do the same, the permission.entries handled by reference in both cases

2020-09-20 14:41 UTC, taki9 commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +          setRefreshFlag(!refreshFlag)
use two parameters insted: submitCallback, cancelCallback
submitCallback is the current callbackFunction
cancelCallback: () => permission.entries.pop()

2020-09-20 14:41 UTC, taki9 commented on apps/sensenet/src/components/view-controls/permission-view.tsx
> +                        setSelectedListItem(`${setOnThisEntry.identity.id}${setOnThisEntry.propagates}`)
its format is interesting 😄

2020-09-21 09:08 UTC, taki9 approved these changes

2020-09-21 09:27 UTC, merged