Permission editor - Force relations
SenseNet/sn-client pull request #852
Opened 2020-09-09 16:43 UTC by pusztaienike

- [X] Implement force realtions set
- [X] Fix Avatar style on inherited entry list

Related backend code for testing:
https://github.com/SenseNet/sensenet/blob/14258d59dbb31b46ba1e4596c6d85d7a9105c50d/src/Storage/Security/PermissionType.cs#L174src/Storage/Security/PermissionType.cs:174
```
See = new PermissionType("See", 0);
Preview = new PermissionType("Preview", 1) { Allows = new[] { See } };
PreviewWithoutWatermark = new PermissionType("PreviewWithoutWatermark", 2) { Allows = new[] { Preview } };
PreviewWithoutRedaction = new PermissionType("PreviewWithoutRedaction", 3) { Allows = new[] { Preview } };
Open = new PermissionType("Open", 4) { Allows = new[] { PreviewWithoutWatermark, PreviewWithoutRedaction } };
OpenMinor = new PermissionType("OpenMinor", 5) { Allows = new[] { Open } };
Save = new PermissionType("Save", 6) { Allows = new[] { OpenMinor } };
Publish = new PermissionType("Publish", 7) { Allows = new[] { OpenMinor } };
ForceCheckin = new PermissionType("ForceCheckin", 8) { Allows = new[] { OpenMinor } };
AddNew = new PermissionType("AddNew", 9) { Allows = new[] { OpenMinor } };
Approve = new PermissionType("Approve", 10) { Allows = new[] { OpenMinor } };
Delete = new PermissionType("Delete", 11) { Allows = new[] { OpenMinor } };
RecallOldVersion = new PermissionType("RecallOldVersion", 12) { Allows = new[] { OpenMinor } };
DeleteOldVersion = new PermissionType("DeleteOldVersion", 13) { Allows = new[] { OpenMinor } };
SeePermissions = new PermissionType("SeePermissions", 14);
SetPermissions = new PermissionType("SetPermissions", 15) { Allows = new[] { SeePermissions } };
RunApplication = new PermissionType("RunApplication", 16);
ManageListsAndWorkspaces = new PermissionType("ManageListsAndWorkspaces", 17) { Allows = new[] { Save, AddNew, DeleteOldVersion } };
TakeOwnership = new PermissionType("TakeOwnership", 18) { Allows = new[] { See } };

```

2020-09-14 09:20 UTC, herflis approved these changes
👑

2020-09-21 18:16 UTC, taki9 requested changes

2020-09-21 18:16 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor-dialog.tsx
> +  const setForcePermissionsAllowed = (localResponseBody: PermissionRequestBody, permissionNameParam: string) => {
setForcedPermissionsToAllowed

2020-09-21 18:16 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor-dialog.tsx
> +      Object.entries(forcePermObject).forEach(([permissionName, toBeSetArray]) => {
forcedPermissions would be better name for toBeSetArray

2020-09-21 18:16 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor-dialog.tsx
> +          toBeSetArray.forEach((toBeSetPermission: keyof PermissionRequestBody) => {
instead of toBeSetPermission use forcedPermission

2020-09-21 18:16 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor-dialog.tsx
> +  const setForcePermissionsAllowed = (localResponseBody: PermissionRequestBody, permissionNameParam: string) => {
please write some description for this function in a comment above it

2020-09-21 18:16 UTC, taki9 commented on apps/sensenet/src/components/dialogs/permission-editor-dialog.tsx
> +  const setForcePermissionsUndefined = (localResponseBody: PermissionRequestBody, permissionNameParam: string) => {
same as in case of setForcePermissionsAllowed

2020-09-22 13:28 UTC, taki9 approved these changes

2020-09-22 13:30 UTC, merged