Prevent multiple upload request on CTDs
SenseNet/sn-client pull request #885
Opened 2020-09-11 13:55 UTC by pusztaienike

2020-09-14 06:55 UTC, herflis approved these changes

2020-09-21 13:55 UTC, taki9 requested changes

2020-09-21 13:55 UTC, taki9 commented on apps/sensenet/src/components/editor/text-editor.tsx
> +      setHasChanges(false)
on catch case, you should set it back to true, not?

2020-09-21 13:55 UTC, taki9 commented on apps/sensenet/src/components/editor/text-editor.tsx
> +      setHasChanges(false)
please fix this in new-file-text-editor too

2020-09-21 18:18 UTC, taki9 approved these changes

2020-09-22 08:01 UTC, merged