Fix copy when no parent selected
SenseNet/sn-client pull request #920
Opened 2020-09-16 15:03 UTC by pusztaienike

2020-09-21 10:07 UTC, herflis approved these changes

2020-09-21 19:06 UTC, taki9 requested changes

2020-09-21 19:06 UTC, taki9 commented on apps/sensenet/src/components/dialogs/copy-move.tsx
> +              const parentItem = list.items.find((item) => item.isParent)
props.currentParent?

2020-09-22 13:29 UTC, taki9 approved these changes

2020-09-22 13:50 UTC, merged