Fix reference link and addnew button on root screen
SenseNet/sn-client pull request #922
Opened 2020-09-16 18:18 UTC by herflis

2020-09-17 09:38 UTC, pusztaienike approved these changes
🦓

2020-09-22 13:56 UTC, taki9 requested changes

2020-09-22 13:56 UTC, taki9 commented on apps/sensenet/src/components/content-list/reference-field.tsx
> +      marginLeft: '1em',
marginRight should be on the icon, because this margin will be there even if no icon rendered

2020-09-22 13:56 UTC, taki9 commented on apps/sensenet/src/components/drawer/PermanentDrawer.tsx
> +              PATHS.root.appPath,
PATHS.custom.appPath.replace(':path', 'root'),
and root can be deleted from PATHS

2020-09-22 16:41 UTC, taki9 approved these changes

2020-09-22 18:07 UTC, merged