Fix checkbox group
SenseNet/sn-client pull request #972
Opened 2020-09-29 12:55 UTC by pusztaienike

2020-09-30 08:03 UTC, taki9 requested changes

2020-09-30 08:03 UTC, taki9 commented on apps/sensenet/src/components/field-controls/CheckboxGroup.tsx
> +          <FormLabel component={'legend' as 'label'} style={{ marginBottom: '10px' }}>
or other good solution is:
```javascript
<InputLabel shrink htmlFor={props.settings.Name}>
  {this.props.settings.DisplayName}
</InputLabel>
```
(I prefer the first one)

2020-10-02 06:54 UTC, taki9 approved these changes

2020-10-02 13:07 UTC, herflis approved these changes
✅

2020-10-05 07:25 UTC, merged