Fix/datefields
SenseNet/sn-client pull request #991
Opened 2020-10-01 14:44 UTC by herflis

2020-10-01 15:13 UTC, pusztaienike approved these changes
🍹

2020-10-02 07:26 UTC, taki9 requested changes

2020-10-02 07:26 UTC, taki9 commented on apps/sensenet/src/components/field-controls/DatePicker.tsx
> +    console.log(moment.utc(date).toISOString())
remove console logs

2020-10-02 07:26 UTC, taki9 commented on packages/sn-controls-react/src/helpers.ts
> +  if (value && value.includes('@@')) {
value?.includes

2020-10-02 07:26 UTC, taki9 commented on packages/sn-controls-react/src/helpers.ts
> +  } else if (value && value.includes('[Script:jScript]')) {
value?.includes

2020-10-05 19:01 UTC, taki9 approved these changes

2020-10-06 08:55 UTC, merged